-- LuaBoost English Localization (Base)
-- This file serves as the default reference for all translations.

LuaBoost_Locale_enUS = {
    -- PART A: Runtime Optimizations
    ["|cff44ff44fast|r"] = "|cff44ff44fast|r",
    ["|cffff4444original|r (fast was %.0f%% slower)"] = "|cffff4444original|r (fast was %.0f%% slower)",
    ["[LuaBoost]|r Math auto-detect results (%d iterations):"] = "[LuaBoost]|r Math auto-detect results (%d iterations):",
    ["  math.floor: orig %6.1f ms, fast %6.1f ms > %s"] = "  math.floor: orig %6.1f ms, fast %6.1f ms > %s",
    ["  math.ceil:  orig %6.1f ms, fast %6.1f ms > %s"] = "  math.ceil:  orig %6.1f ms, fast %6.1f ms > %s",
    ["  math.abs:   orig %6.1f ms, fast %6.1f ms > %s"] = "  math.abs:   orig %6.1f ms, fast %6.1f ms > %s",
    ["  Using fast versions for %d/3 functions. Saved to settings."] = "  Using fast versions for %d/3 functions. Saved to settings.",

    -- PART B: Smart GC Manager
    ["|cff888888[LuaBoost-DBG]|r "] = "|cff888888[LuaBoost-DBG]|r ",
    ["|cff4488ffloading|r"] = "|cff4488ffloading|r",
    ["|cffff4444combat|r"] = "|cffff4444combat|r",
    ["|cff888888idle|r"] = "|cff888888idle|r",
    ["|cff44ff44normal|r"] = "|cff44ff44normal|r",
    ["Idle mode activated"] = "Idle mode activated",
    ["Emergency GC: freed %.1f MB in %.1f ms"] = "Emergency GC: freed %.1f MB in %.1f ms",
    ["Raised threshold to %d MB"] = "Raised threshold to %d MB",

    -- PART C: SpeedyLoad
    ["SpeedyLoad: UnregisterEvent hook installed"] = "SpeedyLoad: UnregisterEvent hook installed",
    ["SpeedyLoad: PLAYER_ENTERING_WORLD priority set"] = "SpeedyLoad: PLAYER_ENTERING_WORLD priority set",

    -- PART D: Benchmark
    ["  %-14s %7.1f ms -> %7.1f ms  (|cff44ff44%.0f%% faster|r)%s"] = "  %-14s %7.1f ms -> %7.1f ms  (|cff44ff44%.0f%% faster|r)%s",
    ["  %-14s %7.1f ms -> %7.1f ms  (|cffff4444%.0f%% slower|r)%s"] = "  %-14s %7.1f ms -> %7.1f ms  (|cffff4444%.0f%% slower|r)%s",
    ["[LuaBoost]|r Running benchmark (%d iterations)..."] = "[LuaBoost]|r Running benchmark (%d iterations)...",
    [" |cff44ff44[active]|r"] = " |cff44ff44[active]|r",
    [" |cff888888[original]|r"] = " |cff888888[original]|r",
    ["[LuaBoost]|r Results (lower ms = better):"] = "[LuaBoost]|r Results (lower ms = better):",

    -- PART E: GUI (Interface Options)
    ["Lua runtime optimizer + smart garbage collector for WoW 3.3.5a."] = "Lua runtime optimizer + smart garbage collector for WoW 3.3.5a.",
    [" | |cff00ff00DLL|r"] = " | |cff00ff00DLL|r",
    ["%s  |  Mem: %s%.1f MB|r  |  %s  |  %s%d|r KB/f%s"] = "%s  |  Mem: %s%.1f MB|r  |  %s  |  %s%d|r KB/f%s",
    ["|cff00ff00ON|r"] = "|cff00ff00ON|r",
    ["|cffff0000OFF|r"] = "|cffff0000OFF|r",
    ["Enable GC Manager"] = "Enable GC Manager",
    ["Master toggle for smart GC."] = "Master toggle for smart GC.",
    ["GC Presets:"] = "GC Presets:",
    ["|cffff8844Weak|r"] = "|cffff8844Weak|r",
    ["|cffffff44Mid|r"] = "|cffffff44Mid|r",
    ["|cff44ff44Strong|r"] = "|cff44ff44Strong|r",
    ["Runtime optimizations are always active."] = "Runtime optimizations are always active.",
    ["Loading Screen Optimization"] = "Loading Screen Optimization",
    ["Enable Fast Loading Screens"] = "Enable Fast Loading Screens",
    ["Temporarily suppresses noisy events during loading screens.\n"] = "Temporarily suppresses noisy events during loading screens.\n",
    ["Reduces CPU work and speeds up zone transitions.\n"] = "Reduces CPU work and speeds up zone transitions.\n",
    ["Restores all events after loading completes."] = "Restores all events after loading completes.",
    ["Mode: %s (%d events)"] = "Mode: %s (%d events)",
    ["|cff44ff44Safe|r"] = "|cff44ff44Safe|r",
    ["|cffff8844Aggressive|r"] = "|cffff8844Aggressive|r",
    ["|cffff4444GetFramesRegisteredForEvent not available — SpeedyLoad disabled.|r"] = "|cffff4444GetFramesRegisteredForEvent not available — SpeedyLoad disabled.|r",
    ["GC Settings"] = "GC Settings",
    ["GC Settings|r"] = "GC Settings|r",
    ["Step Sizes (KB collected per frame)"] = "Step Sizes (KB collected per frame)",
    ["Memory Scan Interval (sec)"] = "Memory Scan Interval (sec)",
    ["custom"] = "custom",
    ["Normal Step"] = "Normal Step",
    ["GC per frame during normal gameplay."] = "GC per frame during normal gameplay.",
    ["Combat Step"] = "Combat Step",
    ["GC per frame in combat (keep low to protect frametime)."] = "GC per frame in combat (keep low to protect frametime).",
    ["Idle Step"] = "Idle Step",
    ["GC per frame while AFK/idle."] = "GC per frame while AFK/idle.",
    ["Loading Step"] = "Loading Step",
    ["GC per frame during loading screens (no rendering)."] = "GC per frame during loading screens (no rendering).",
    ["Thresholds"] = "Thresholds",
    ["Emergency Full GC (MB)"] = "Emergency Full GC (MB)",
    ["Force full GC outside combat when memory exceeds this.\n"] = "Force full GC outside combat when memory exceeds this.\n",
    ["Set higher (300-500+) if you use many addons to avoid long freezes."] = "Set higher (300-500+) if you use many addons to avoid long freezes.",
    ["Idle Mode Timeout (sec)"] = "Idle Mode Timeout (sec)",
    ["Idle Timeout (sec)"] = "Idle Timeout (sec)",
    ["Seconds without activity before idle mode."] = "Seconds without activity before idle mode.",
    ["Tools"] = "Tools",
    ["Tools & Diagnostics|r"] = "Tools & Diagnostics|r",
    ["Debug mode (GC info in chat)"] = "Debug mode (GC info in chat)",
    ["Shows GC mode changes, SpeedyLoad activity, and emergency collections."] = "Shows GC mode changes, SpeedyLoad activity, and emergency collections.",
    ["Intercept collectgarbage() calls"] = "Intercept collectgarbage() calls",
    ["Blocks full GC calls triggered by other addons.\n"] = "Blocks full GC calls triggered by other addons.\n",
    ["|cffff4444WARNING:|r Causes taint with ElvUI and secure frames.\n"] = "|cffff4444WARNING:|r Causes taint with ElvUI and secure frames.\n",
    ["Leave OFF if you see 'action blocked' errors."] = "Leave OFF if you see 'action blocked' errors.",
    ["Block UpdateAddOnMemoryUsage()"] = "Block UpdateAddOnMemoryUsage()",
    ["Blocks heavy addon memory scans.\n"] = "Blocks heavy addon memory scans.\n",
    ["MemUsage Min Interval (sec)"] = "MemUsage Min Interval (sec)",
    ["Minimum interval between UpdateAddOnMemoryUsage() calls."] = "Minimum interval between UpdateAddOnMemoryUsage() calls.",
    ["Force Full GC Now"] = "Force Full GC Now",
    ["Run Benchmark"] = "Run Benchmark",
    ["Reset All to Defaults"] = "Reset All to Defaults",
    ["Math Optimizations"] = "Math Optimizations",
    ["|cff44ff44done|r"] = "|cff44ff44done|r",
    ["|cffffff44pending|r"] = "|cffffff44pending|r",
    ["Auto-detect math on first run"] = "Auto-detect math on first run",
    ["Runs a quick micro-benchmark on first login to determine\n"] = "Runs a quick micro-benchmark on first login to determine\n",
    ["whether fast math replacements are actually faster on your CPU.\n"] = "whether fast math replacements are actually faster on your CPU.\n",
    ["Result is saved — bench only runs once."] = "Result is saved — bench only runs once.",
    ["Re-run Math Auto-detect"] = "Re-run Math Auto-detect",

    -- PART F: Slash Commands
    ["  GC: %s | Mode: %s | Mem: %.1f MB | Step: %d KB/f"] = "  GC: %s | Mode: %s | Mem: %.1f MB | Step: %d KB/f",
    ["  Protection: interceptGC=%s, blockMemUsage=%s"] = "  Protection: interceptGC=%s, blockMemUsage=%s",
    ["on"] = "on",
    ["off"] = "off",
    ["  SpeedyLoad: %s (%s, %d events)"] = "  SpeedyLoad: %s (%s, %d events)",
    ["aggressive"] = "aggressive",
    ["safe"] = "safe",
    ["  Math: %d/3 fast | bench: %s"] = "  Math: %d/3 fast | bench: %s",
    ["done"] = "done",
    ["pending"] = "pending",
    ["  wow_optimize.dll: |cff00ff00CONNECTED|r"] = "  wow_optimize.dll: |cff00ff00CONNECTED|r",
    ["  wow_optimize.dll: |cffaaaaaaNOT DETECTED|r"] = "  wow_optimize.dll: |cffaaaaaaNOT DETECTED|r",
    ["/lb help|r"] = "/lb help|r",
    ["[LuaBoost]|r GC Stats:"] = "[LuaBoost]|r GC Stats:",
    ["  Memory: %.0f KB (%.1f MB)"] = "  Memory: %.0f KB (%.1f MB)",
    ["  Mode: %s | Step: %d KB/f"] = "  Mode: %s | Step: %d KB/f",
    ["  Lua steps: %d | Emergency: %d | Full: %d"] = "  Lua steps: %d | Emergency: %d | Full: %d",
    ["  Loading: %s | Idle: %s | Combat: %s"] = "  Loading: %s | Idle: %s | Combat: %s",
    ["yes"] = "yes",
    ["no"] = "no",
    ["  DLL: mem=%.0fKB steps=%d full=%d mode=%s"] = "  DLL: mem=%.0fKB steps=%d full=%d mode=%s",
    ["[LuaBoost]|r Pool: %d acquired, %d released, %d created, %d available"] = "[LuaBoost]|r Pool: %d acquired, %d released, %d created, %d available",
    ["GC Manager: "] = "GC Manager: ",
    ["SpeedyLoad: %s (%s, %d events)"] = "SpeedyLoad: %s (%s, %d events)",
    ["SpeedyLoad: |cff00ff00ON|r (|cff44ff44safe|r, "] = "SpeedyLoad: |cff00ff00ON|r (|cff44ff44safe|r, ",
    [" events)"] = " events)",
    ["SpeedyLoad: |cff00ff00ON|r (|cffff8844aggressive|r, "] = "SpeedyLoad: |cff00ff00ON|r (|cffff8844aggressive|r, ",
    ["[LuaBoost]|r Math functions:"] = "[LuaBoost]|r Math functions:",
    ["|cff44ff44fast (LuaBoost)|r"] = "|cff44ff44fast (LuaBoost)|r",
    ["|cff888888original (Lua/C)|r"] = "|cff888888original (Lua/C)|r",
    ["  Auto-detect: %s | Bench: %s"] = "  Auto-detect: %s | Bench: %s",
    ["/lb mathbench|r to re-run detection"] = "/lb mathbench|r to re-run detection",
    ["[LuaBoost]|r Commands:"] = "[LuaBoost]|r Commands:",
    ["  /lb              — status"] = "  /lb              — status",
    ["  /lb bench        — benchmark"] = "  /lb bench        — benchmark",
    ["  /lb gc           — GC stats"] = "  /lb gc           — GC stats",
    ["  /lb pool         — table pool stats"] = "  /lb pool         — table pool stats",
    ["  /lb toggle       — enable/disable GC manager"] = "  /lb toggle       — enable/disable GC manager",
    ["  /lb force        — force full GC now"] = "  /lb force        — force full GC now",
    ["  /lb sl           — toggle SpeedyLoad"] = "  /lb sl           — toggle SpeedyLoad",
    ["  /lb sl safe      — SpeedyLoad safe mode"] = "  /lb sl safe      — SpeedyLoad safe mode",
    ["  /lb sl agg       — SpeedyLoad aggressive mode"] = "  /lb sl agg       — SpeedyLoad aggressive mode",
    ["  /lb math         — math optimization status"] = "  /lb math         — math optimization status",
    ["  /lb mathbench    — re-run math auto-detect"] = "  /lb mathbench    — re-run math auto-detect",
    ["  /lb settings     — open GC settings"] = "  /lb settings     — open GC settings",

    -- PART G: Initialization
    ["GC:"] = "GC:",
    ["GC:|cffff0000OFF|r"] = "GC:|cffff0000OFF|r",
    ["Math:%s%d/3|r"] = "Math:%s%d/3|r",
    ["Math:|cffffff44detecting...|r"] = "Math:|cffffff44detecting...|r",
    ["/lb|r help"] = "/lb|r help",
    ["[LuaBoost]|r |cffff8844WARNING:|r SmartGC detected. Disable SmartGC to avoid conflicts."] = "[LuaBoost]|r |cffff8844WARNING:|r SmartGC detected. Disable SmartGC to avoid conflicts.",
}
