-- LuaBoost Korean Localization
-- Contributed by [nadugi]

LuaBoost_Locale_koKR = {
    -- PART A: Runtime Optimizations
    ["|cff44ff44fast|r"] = "|cff44ff44최적화 버전 사용|r",
    ["|cffff4444original|r (fast was %.0f%% slower)"] = "|cffff4444기본 버전 사용|r (최적화 버전이 %.0f%% 더 느림)",
    ["[LuaBoost]|r Math auto-detect results (%d iterations):"] = "[LuaBoost]|r 수학 연산 자동 감지 결과 (%d회 반복):",
    ["  math.floor: orig %6.1f ms, fast %6.1f ms > %s"] = "  math.floor: 기본 %6.1f ms, 최적화 %6.1f ms > %s",
    ["  math.ceil:  orig %6.1f ms, fast %6.1f ms > %s"] = "  math.ceil:  기본 %6.1f ms, 최적화 %6.1f ms > %s",
    ["  math.abs:   orig %6.1f ms, fast %6.1f ms > %s"] = "  math.abs:   기본 %6.1f ms, 최적화 %6.1f ms > %s",
    ["  Using fast versions for %d/3 functions. Saved to settings."] = " 3개 중 %d개 함수에 최적화 버전을 적용했습니다. 설정이 저장되었습니다.",

    -- PART B: Smart GC Manager
    ["|cff888888[LuaBoost-DBG]|r "] = "|cff888888[LuaBoost-디버그]|r ",
    ["|cff4488ffloading|r"] = "|cff4488ff로딩 중|r",
    ["|cffff4444combat|r"] = "|cffff4444전투 중|r",
    ["|cff888888idle|r"] = "|cff888888대기 중|r",
    ["|cff44ff44normal|r"] = "|cff44ff44일반|r",
    ["Idle mode activated"] = "대기 모드 활성화",
    ["Emergency GC: freed %.1f MB in %.1f ms"] = "긴급 메모리 정리: %.1f MB 해제 완료 (소요 시간: %.1f ms)",
    ["Raised threshold to %d MB"] = "정리 지연 발생으로 임계값을 %d MB로 상향 조정합니다.",

    -- PART C: SpeedyLoad
    ["SpeedyLoad: UnregisterEvent hook installed"] = "SpeedyLoad: 이벤트 차단 기능이 준비되었습니다.",
    ["SpeedyLoad: PLAYER_ENTERING_WORLD priority set"] = "SpeedyLoad: 지역 이동 최적화 우선순위가 설정되었습니다.",

    -- PART D: Benchmark
    ["  %-14s %7.1f ms -> %7.1f ms  (|cff44ff44%.0f%% faster|r)%s"] = "  %-14s %7.1f ms -> %7.1f ms  (|cff44ff44%.0f%% 빠름|r)%s",
    ["  %-14s %7.1f ms -> %7.1f ms  (|cffff4444%.0f%% slower|r)%s"] = "  %-14s %7.1f ms -> %7.1f ms  (|cffff4444%.0f%% 느림|r)%s",
    ["[LuaBoost]|r Running benchmark (%d iterations)..."] = "[LuaBoost]|r 벤치마크를 시작합니다 (%d회 반복)...",
    [" |cff44ff44[active]|r"] = " |cff44ff44[활성]|r",
    [" |cff888888[original]|r"] = " |cff888888[기본값]|r",
    ["[LuaBoost]|r Results (lower ms = better):"] = "[LuaBoost]|r 테스트 결과 (낮을수록 좋음):",

    -- PART E: GUI (Interface Options)
    ["Lua runtime optimizer + smart garbage collector for WoW 3.3.5a."] = "WoW 3.3.5a를 위한 Lua 런타임 최적화 및 스마트 메모리 관리 도구",
    [" | |cff00ff00DLL|r"] = " | |cff00ff00DLL 연결됨|r",
    ["%s  |  Mem: %s%.1f MB|r  |  %s  |  %s%d|r KB/f%s"] = "상태: %s | 메모리: %s%.1f MB|r | 모드: %s | 초당 정리량: %s%d|r KB/f%s",
    ["|cff00ff00ON|r"] = "|cff00ff00작동 중|r",
    ["|cffff0000OFF|r"] = "|cffff0000중지됨|r",
    ["Enable GC Manager"] = "GC 관리자 활성화",
    ["Master toggle for smart GC."] = "스마트 가비지 컬렉션 기능을 켜거나 끕니다.",
    ["GC Presets:"] = "정리 강도 설정(프리셋):",
    ["|cffff8844Weak|r"] = "|cffff8844약하게|r",
    ["|cffffff44Mid|r"] = "|cffffff44중간|r",
    ["|cff44ff44Strong|r"] = "|cff44ff44강하게|r",
    ["Runtime optimizations are always active."] = "런타임 최적화(수학 연산 등)는 항상 활성화되어 있습니다.",
    ["Loading Screen Optimization"] = "로딩 화면 최적화 (SpeedyLoad)",
    ["Enable Fast Loading Screens"] = "1. 빠른 로딩 화면 사용",
    ["Temporarily suppresses noisy events during loading screens.\n"] = "로딩 중 불필요한 시스템 이벤트를 일시 차단하여 CPU 부하를 줄이고\n",
    ["Reduces CPU work and speeds up zone transitions.\n"] = "지역 이동 속도를 향상시킵니다.\n",
    ["Restores all events after loading completes."] = "로딩이 끝나면 자동으로 복구됩니다.",
    ["Mode: %s (%d events)"] = "현재 모드: %s (차단 이벤트: %d개)",
    ["|cff44ff44Safe|r"] = "|cff44ff44안전 모드|r",
    ["|cffff8844Aggressive|r"] = "|cffff8844공격 모드|r",
    ["|cffff4444GetFramesRegisteredForEvent not available — SpeedyLoad disabled.|r"] = "|cffff4444[경고] 함수 제한으로 SpeedyLoad가 비활성화되었습니다.|r",
    ["GC Settings"] = "상세 정리 설정",
    ["GC Settings|r"] = "상세 정리 설정|r",
    ["Step Sizes (KB collected per frame)"] = "단계별 정리량 (프레임당 KB)",
    ["Memory Scan Interval (sec)"] = "메모리 갱신 최소 간격 (초)",
    ["custom"] = "사용자 설정",
    ["Normal Step"] = "1. 일반 단계",
    ["GC per frame during normal gameplay."] = "평상시 게임 플레이 중 프레임당 정리량입니다.",
    ["Combat Step"] = "2. 전투 단계",
    ["GC per frame in combat (keep low to protect frametime)."] = "전투 중 프레임당 정리량입니다. (프레임 드랍 방지를 위해 낮게 유지 권장)",
    ["Idle Step"] = "3. 대기 상태 단계",
    ["GC per frame while AFK/idle."] = "자리비움 또는 대기 상태일 때의 프레임당 정리량입니다.",
    ["Loading Step"] = "4. 로딩 중 단계",
    ["GC per frame during loading screens (no rendering)."] = "로딩 화면(지역 이동) 중의 프레임당 정리량입니다.",
    ["Thresholds"] = "임계값 설정",
    ["Emergency Full GC (MB)"] = "5. 긴급 전체 정리 기준 (MB)",
    ["Force full GC outside combat when memory exceeds this.\n"] = "전투 중이 아닐 때 메모리가 이 수치를 초과하면 전체 정리를 강제합니다.\n",
    ["Set higher (300-500+) if you use many addons to avoid long freezes."] = "애드온을 많이 사용한다면 300-500 이상으로 높게 설정하여 멈춤 현상을 방지하세요.",
    ["Idle Mode Timeout (sec)"] = "6. 대기모드 전환시간(초)",
    ["Idle Timeout (sec)"] = "6. 대기모드 전환시간(초)",
    ["Seconds without activity before idle mode."] = "아무 활동이 없을 때 대기 모드로 전환될 시간입니다.",
    ["Tools"] = "도구 및 진단",
    ["Tools & Diagnostics|r"] = "도구 및 진단|r",
    ["Debug mode (GC info in chat)"] = "1. |cffffffff디버그 모드|r (채팅창 알림)",
    ["Shows GC mode changes, SpeedyLoad activity, and emergency collections."] = "정리 모드 변경, SpeedyLoad 작동 및 긴급 정리 상황을 채팅창에 표시합니다.",
    ["Intercept collectgarbage() calls"] = "2. |cffffffff타 애드온의 GC 호출 차단|r",
    ["Blocks full GC calls triggered by other addons.\n"] = "다른 애드온이 강제로 전체 정리를 호출하는 것을 차단합니다.\n",
    ["|cffff4444WARNING:|r Causes taint with ElvUI and secure frames.\n"] = "|cffff4444주의:|r ElvUI 등 특정 UI 사용 시 '액션 차단' 오류가 발생할 수 있습니다.\n",
    ["Leave OFF if you see 'action blocked' errors."] = "오류 발생 시 이 기능을 끄세요.",
    ["Block UpdateAddOnMemoryUsage()"] = "3. |cffffffff메모리 사용량 갱신 차단|r",
    ["Blocks heavy addon memory scans.\n"] = "성능에 부하를 주는 애드온 메모리 스캔 작업을 차단합니다.\n",
    ["MemUsage Min Interval (sec)"] = "메모리 갱신 최소 간격 (초)",
    ["Minimum interval between UpdateAddOnMemoryUsage() calls."] = "메모리 사용량 스캔 사이의 최소 대기 시간입니다.",
    ["Force Full GC Now"] = "지금 전체 정리 실행",
    ["Run Benchmark"] = "벤치마크 실행",
    ["Reset All to Defaults"] = "모든 설정 초기화",
    ["Math Optimizations"] = "수학 연산 최적화 상태",
    ["|cff44ff44done|r"] = "|cff44ff44완료|r",
    ["|cffffff44pending|r"] = "|cffffff44대기 중|r",
    ["Auto-detect math on first run"] = "최초 실행 시 수학 연산 최적화 자동 감지",
    ["Runs a quick micro-benchmark on first login to determine\n"] = "첫 로그인 시 마이크로 벤치마크를 수행하여\n",
    ["whether fast math replacements are actually faster on your CPU.\n"] = "최적화된 수학 함수가 현재 CPU에서 실제로 더 빠른지 확인합니다.\n",
    ["Result is saved — bench only runs once."] = "최초 1회만 측정하며, 결과 값은 설정에 저장됩니다.",
    ["Re-run Math Auto-detect"] = "연산 최적화 다시 감지",

    -- PART F: Slash Commands
    ["  GC: %s | Mode: %s | Mem: %.1f MB | Step: %d KB/f"] = "  상태: %s | 모드: %s | 메모리: %.1f MB | 단계: %d KB/f",
    ["  Protection: interceptGC=%s, blockMemUsage=%s"] = "  보호 설정: GC 차단=%s, 메모리 갱신 차단=%s",
    ["on"] = "사용",
    ["off"] = "미사용",
    ["  SpeedyLoad: %s (%s, %d events)"] = "  SpeedyLoad: %s (%s 모드, %d개 이벤트)",
    ["aggressive"] = "공격적",
    ["safe"] = "안전",
    ["  Math: %d/3 fast | bench: %s"] = "  연산 최적화: %d/3 항목 활성 | 측정 상태: %s",
    ["done"] = "|cff44ff44완료|r",
    ["pending"] = "|cffffff44대기 중|r",
    ["  wow_optimize.dll: |cff00ff00CONNECTED|r"] = "  wow_optimize.dll: |cff00ff00연결됨|r",
    ["  wow_optimize.dll: |cffaaaaaaNOT DETECTED|r"] = "  wow_optimize.dll: |cffaaaaaa미감지 (기본 엔진 작동)|r",
    ["/lb help|r"] = "도움말은 /lb help|r를 입력하세요.",
    ["[LuaBoost]|r GC Stats:"] = "[LuaBoost]|r 가비지 컬렉션(GC) 통계:",
    ["  Memory: %.0f KB (%.1f MB)"] = "  현재 메모리: %.0f KB (%.1f MB)",
    ["  Mode: %s | Step: %d KB/f"] = "  현재 모드: %s | 단계별 정리량: %d KB/f",
    ["  Lua steps: %d | Emergency: %d | Full: %d"] = "  Lua 단계: %d | 긴급 정리: %d | 전체 정리: %d",
    ["  Loading: %s | Idle: %s | Combat: %s"] = "  로딩 중: %s | 대기 중: %s | 전투 중: %s",
    ["yes"] = "예",
    ["no"] = "아니오",
    ["  DLL: mem=%.0fKB steps=%d full=%d mode=%s"] = "  DLL 정보: 메모리=%.0fKB, 단계=%d, 전체정리=%d, 모드=%s",
    ["[LuaBoost]|r Pool: %d acquired, %d released, %d created, %d available"] = "[LuaBoost]|r 테이블 풀: 사용 중 %d, 반환됨 %d, 생성됨 %d, 가용 %d",
    ["GC Manager: "] = "GC 관리자 상태: ",
    ["SpeedyLoad: %s (%s, %d events)"] = "SpeedyLoad: %s (%s 모드, %d개 이벤트)",
    ["SpeedyLoad: |cff00ff00ON|r (|cff44ff44safe|r, "] = "SpeedyLoad: |cff00ff00켜짐|r (|cff44ff44안전|r 모드, ",
    [" events)"] = "개 이벤트)",
    ["SpeedyLoad: |cff00ff00ON|r (|cffff8844aggressive|r, "] = "SpeedyLoad: |cff00ff00켜짐|r (|cffff8844공격적|r 모드, ",
    ["[LuaBoost]|r Math functions:"] = "[LuaBoost]|r 수학 연산 최적화:",
    ["|cff44ff44fast (LuaBoost)|r"] = "|cff44ff44최적화 적용 중|r",
    ["|cff888888original (Lua/C)|r"] = "|cff888888기본 엔진 사용 중|r",
    ["  Auto-detect: %s | Bench: %s"] = "  자동 감지: %s | 측정 결과: %s",
    ["/lb mathbench|r to re-run detection"] = "/lb mathbench|r를 입력하여 다시 측정하세요.",
    ["[LuaBoost]|r Commands:"] = "[LuaBoost]|r 명령어 도움말:",
    ["  /lb              — status"] = "  /lb              - 현재 상태 및 정보 표시",
    ["  /lb bench        — benchmark"] = "  /lb bench        - CPU 연산 성능 벤치마크",
    ["  /lb gc           — GC stats"] = "  /lb gc           - 상세 가비지 컬렉션 통계",
    ["  /lb pool         — table pool stats"] = "  /lb pool         - 테이블 재사용 풀 상태",
    ["  /lb toggle       — enable/disable GC manager"] = "  /lb toggle       - GC 관리자 기능 켜기/끄기",
    ["  /lb force        — force full GC now"] = "  /lb force        - 수동으로 전체 메모리 정리",
    ["  /lb sl           — toggle SpeedyLoad"] = "  /lb sl           - 로딩 가속(SpeedyLoad) 토글",
    ["  /lb sl safe      — SpeedyLoad safe mode"] = "  /lb sl safe      - 로딩 가속: 안전 모드 설정",
    ["  /lb sl agg       — SpeedyLoad aggressive mode"] = "  /lb sl agg       - 로딩 가속: 공격적 모드 설정",
    ["  /lb math         — math optimization status"] = "  /lb math         - 수학 연산 최적화 상태 확인",
    ["  /lb mathbench    — re-run math auto-detect"] = "  /lb mathbench    - 연산 성능 자동 감지 재실행",
    ["  /lb settings     — open GC settings"] = "  /lb settings     - 상세 설정 창 열기",

    -- PART G: Initialization
    ["GC:"] = "정리:",
    ["GC:|cffff0000OFF|r"] = "정리:|cffff0000OFF|r",
    ["Math:%s%d/3|r"] = "최적화:%s%d/3|r",
    ["Math:|cffffff44detecting...|r"] = "최적화:|cffffff44성능 측정 중...|r",
    ["/lb|r help"] = "/lb help|r 도움말",
    ["[LuaBoost]|r |cffff8844WARNING:|r SmartGC detected. Disable SmartGC to avoid conflicts."] = "[LuaBoost]|r |cffff8844경고:|r SmartGC 애드온이 감지되었습니다. 충돌을 방지하려면 SmartGC를 비활성화하세요.",
}
